pyuic5 -o src\ui\main_window_ui.py src\ui\main_window.ui
pyuic5 -o src\ui\ctrl_panel_ui.py src\ui\ctrl_panel.ui
pyuic5 -o src\ui\device_setting_ui.py src\ui\device_setting.ui
pyuic5 -o src\ui\network_setting_ui.py src\ui\network_setting.ui
pyuic5 -o src\ui\setting_ui.py src\ui\setting.ui
pyuic5 -o src\ui\setting_ui.py src\ui\setting.ui
pyuic5 -o src\ui\dcdc_panel_ui.py src\ui\dcdc_panel.ui
pyuic5 -o src\ui\history_panel_ui.py src\ui\history_panel.ui
pyuic5 -o src\ui\full_history_panel_ui.py src\ui\full_history_panel.ui