# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\ui\device_setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(516, 430)
        self.spinbox_speed = DoubleSpinBox(Form)
        self.spinbox_speed.setGeometry(QtCore.QRect(235, 52, 170, 44))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinbox_speed.sizePolicy().hasHeightForWidth())
        self.spinbox_speed.setSizePolicy(sizePolicy)
        self.spinbox_speed.setMinimumSize(QtCore.QSize(0, 44))
        self.spinbox_speed.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.spinbox_speed.setFrame(True)
        self.spinbox_speed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinbox_speed.setReadOnly(False)
        self.spinbox_speed.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinbox_speed.setProperty("showGroupSeparator", False)
        self.spinbox_speed.setPrefix("")
        self.spinbox_speed.setMinimum(-3000.0)
        self.spinbox_speed.setMaximum(3000.0)
        self.spinbox_speed.setSingleStep(10.0)
        self.spinbox_speed.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spinbox_speed.setObjectName("spinbox_speed")
        self.label_speed = SubtitleLabel(Form)
        self.label_speed.setGeometry(QtCore.QRect(60, 60, 169, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_speed.sizePolicy().hasHeightForWidth())
        self.label_speed.setSizePolicy(sizePolicy)
        self.label_speed.setMinimumSize(QtCore.QSize(0, 0))
        self.label_speed.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_speed.setObjectName("label_speed")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_speed.setText(_translate("Form", "速度："))
from qfluentwidgets import DoubleSpinBox, SubtitleLabel
